name: Run tests and upload results

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.gitattributes'
      - '*.md'
      - '*.rst'
      - 'LICENSE'
      - 'protobuf_list.txt'
      - 'docs/**'
      - 'protobufs/**'
      - 'recipes/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '.gitattributes'
      - '*.md'
      - '*.rst'
      - 'LICENSE'
      - 'protobuf_list.txt'
      - 'docs/**'
      - 'protobufs/**'
      - 'recipes/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VERSION: 2.2.1

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - name: Set up python environment
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          pipx install poetry==${{ env.POETRY_VERSION }}
          poetry install --extras client --with dev --no-interaction --no-ansi

      - name: Run Tests (generate JUnit XML)
        run: |
          python -c "import os; os.makedirs('reports', exist_ok=True)"
          poetry run pytest -p no:cov --junitxml=reports/junit.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: reports/junit.xml